modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="biding-piece"
version="1.0.0"
displayName="Biding Piece"
authors="Albertux2"
description='''
Biding spaces where users can bid. Leader decides highest bid and winner.
'''

[[dependencies.biding-piece]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.biding-piece]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
